title: "KG's adventure game for funzies"
markdown: kramdown
theme: minima
include: [".md"]
kramdown:
  toc_levels: 1..3 # Include headers from h1 to h3 in the ToC
  auto_ids: true   # Automatically generate IDs for headers
plugins:
  - jekyll-feed
